names = [
    ".tokana",
    ".假名",
    ".假名化",
    ".大佐说",
    ".太君说",
]
description = "试着把中文按发音转换成片假名"

examples = [
    { input = ".大佐说 中国有一句古话，识时务者，为俊杰" },
    { input = ".假名化 你好，谢谢，小笼包，再见 -风格 2" },
    { input = ".假名化 山中无老虎，猴子称霸王 -s3" },
]

options = [
    { names = ["-s", "-style", "-风格"], params = "编号", description = "可选 1,2,3 三种风格，默认为风格 1"},
    { names = ["-s1", "-s2", "-s3"], description = "切换到风格 1,2,3" },
]
