names = [
    ".chat",
    ".ai"
]
description = """
基于DeepSeek API的AI对话
"""

examples = [
    { input = ".chat 吃 250 个包子会怎么样" },
    { input = ".chat 抽卡面包的效果？" },
    { plain = "```rpk .chat -r``` 抽卡面包的效果？" },
    { input = ".chat -连接 @群友 前面说了啥" },
    { input = ".chat -断开 @群友" },
]

options = [
    { names = ["-r", "-reset"], description = "重新开始对话" },
    { names = ["-l", "-link", "-连接", "-连"], params = "@群友", description = "连接群友的对话" },
    { names = ["-unl", "-unlink", "-断开", "-断"], params = "@群友", description = "断开与群友对话的连接" },
]

misc = """
不同问题的思考长度不同，有时可能要等待较长时间才能得到回复

可以使用 ```rpk .chatlog``` 查看对话记录，详见 ```rpk .help chatlog```
"""
