names = [
    ".choose",
    ".选",
    ".抽",
    ".挑",
    ".帮我决定",
]
description = "从给出的选项中挑一个"

examples = [
    { input = ".choose 石头 剪刀 布" },
    { input = ".选 正/反" },
    { input = ".挑 红桃、黑桃、梅花、方片" },
    { input = ".抽 末吉，末吉，末吉，末吉，小吉，小吉，小吉，中吉，中吉，大吉，大凶" },
]
